# Generated by Django 5.2.1 on 2025-11-11 19:09

from django.db import migrations


def create_initial_positions(apps, schema_editor):
    """Create initial positions in the database"""
    Position = apps.get_model("accounts", "Position")
    
    positions = [
        "Professor",
        "Dotsent",
        "Katta o'qituvchi",
        "Assistent",
        "Stajer-o'qituvchi",
    ]
    
    for position_name in positions:
        Position.objects.get_or_create(name=position_name)


def reverse_create_positions(apps, schema_editor):
    """Remove initial positions from the database"""
    Position = apps.get_model("accounts", "Position")
    
    positions = [
        "Professor",
        "Dotsent",
        "Katta o'qituvchi",
        "Assistent",
        "Stajer-o'qituvchi",
    ]
    
    Position.objects.filter(name__in=positions).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_initial_positions, reverse_create_positions),
    ]
