# Generated by Django 5.2.8 on 2025-11-11 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("year", models.PositiveIntegerField()),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("UZ", "O'zbek"),
                            ("RU", "Rus"),
                            ("EN", "Ingliz"),
                            ("OTHER", "Boshqa"),
                        ],
                        default="UZ",
                        max_length=16,
                    ),
                ),
                ("is_department_visible", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("publisher", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[("LOCAL", "Mahalliy"), ("INTERNATIONAL", "Xalqaro")],
                        max_length=32,
                    ),
                ),
                ("file", models.FileField(upload_to="works/certificates/")),
                ("description", models.TextField(blank=True)),
                (
                    "authors",
                    models.ManyToManyField(
                        blank=True,
                        related_name="authored_%(class)s",
                        to="accounts.profile",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="accounts.department",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_%(class)s",
                        to="accounts.profile",
                    ),
                ),
            ],
            options={
                "ordering": ("-year", "-created_at"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MethodicalWork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("year", models.PositiveIntegerField()),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("UZ", "O'zbek"),
                            ("RU", "Rus"),
                            ("EN", "Ingliz"),
                            ("OTHER", "Boshqa"),
                        ],
                        default="UZ",
                        max_length=16,
                    ),
                ),
                ("is_department_visible", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("publisher", models.CharField(blank=True, max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("INSTRUCTION", "Uslubiy ko'rsatma"),
                            ("GUIDE", "Uslubiy qo'llanma"),
                            ("STUDY_GUIDE", "O'quv qo'llanma"),
                            ("TEXTBOOK", "Darslik"),
                        ],
                        max_length=32,
                    ),
                ),
                ("file", models.FileField(upload_to="works/methodical/")),
                (
                    "permission_file",
                    models.FileField(
                        blank=True, null=True, upload_to="works/methodical/permissions/"
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "authors",
                    models.ManyToManyField(
                        blank=True,
                        related_name="authored_%(class)s",
                        to="accounts.profile",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="accounts.department",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_%(class)s",
                        to="accounts.profile",
                    ),
                ),
            ],
            options={
                "ordering": ("-year", "-created_at"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ResearchWork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("year", models.PositiveIntegerField()),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("UZ", "O'zbek"),
                            ("RU", "Rus"),
                            ("EN", "Ingliz"),
                            ("OTHER", "Boshqa"),
                        ],
                        default="UZ",
                        max_length=16,
                    ),
                ),
                ("is_department_visible", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("venue", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("LOCAL_ARTICLE", "Mahalliy maqola"),
                            ("FOREIGN_ARTICLE", "Xorijiy maqola"),
                            ("LOCAL_THESIS", "Mahalliy tezis"),
                            ("FOREIGN_THESIS", "Xorijiy tezis"),
                            ("LOCAL_MONOGRAPH", "Mahalliy monografiya"),
                            ("FOREIGN_MONOGRAPH", "Xorijiy monografiya"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="works/research/"
                    ),
                ),
                ("link", models.URLField(blank=True)),
                (
                    "authors",
                    models.ManyToManyField(
                        blank=True,
                        related_name="authored_%(class)s",
                        to="accounts.profile",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="accounts.department",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_%(class)s",
                        to="accounts.profile",
                    ),
                ),
            ],
            options={
                "ordering": ("-year", "-created_at"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SoftwareCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("year", models.PositiveIntegerField()),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("UZ", "O'zbek"),
                            ("RU", "Rus"),
                            ("EN", "Ingliz"),
                            ("OTHER", "Boshqa"),
                        ],
                        default="UZ",
                        max_length=16,
                    ),
                ),
                ("is_department_visible", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("issued_by", models.CharField(max_length=255)),
                ("approval_date", models.DateField()),
                ("cert_number", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[("DGU", "DGU"), ("BGU", "BGU")], max_length=32
                    ),
                ),
                ("file", models.FileField(upload_to="works/software-certificates/")),
                (
                    "authors",
                    models.ManyToManyField(
                        blank=True,
                        related_name="authored_%(class)s",
                        to="accounts.profile",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="accounts.department",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_%(class)s",
                        to="accounts.profile",
                    ),
                ),
            ],
            options={
                "ordering": ("-year", "-created_at"),
                "abstract": False,
            },
        ),
    ]
