# Generated by Django 5.2.1 on 2025-11-13 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("works", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="methodicalwork",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to="works/methodical/"
            ),
        ),
    ]
