# Generated by Django 5.2.1 on 2025-11-13 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("works", "0002_alter_methodicalwork_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificate",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to="works/certificates/"
            ),
        ),
        migrations.AlterField(
            model_name="certificate",
            name="publisher",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
