# Generated by Django 5.2.1 on 2025-11-13 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("works", "0003_alter_certificate_file_alter_certificate_publisher"),
    ]

    operations = [
        migrations.AlterField(
            model_name="softwarecertificate",
            name="approval_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="softwarecertificate",
            name="cert_number",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="softwarecertificate",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to="works/software-certificates/"
            ),
        ),
        migrations.AlterField(
            model_name="softwarecertificate",
            name="issued_by",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
