# Generated by Django 5.2.1 on 2025-11-13 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("works", "0004_alter_softwarecertificate_approval_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificate",
            name="year",
            field=models.CharField(
                help_text="O'quv yili formatida (masalan: 2024-2025)", max_length=9
            ),
        ),
        migrations.AlterField(
            model_name="methodicalwork",
            name="year",
            field=models.CharField(
                help_text="O'quv yili formatida (masalan: 2024-2025)", max_length=9
            ),
        ),
        migrations.AlterField(
            model_name="researchwork",
            name="year",
            field=models.CharField(
                help_text="O'quv yili formatida (masalan: 2024-2025)", max_length=9
            ),
        ),
        migrations.AlterField(
            model_name="softwarecertificate",
            name="year",
            field=models.CharField(
                help_text="O'quv yili formatida (masalan: 2024-2025)", max_length=9
            ),
        ),
    ]
