import type {
  User,
  MethodicalWork,
  ResearchWork,
  Certificate,
  SoftwareCertificate,
  File,
} from "./types"

// Mock Users with demo credentials
export const mockUsers: User[] = [
  {
    id: 1,
    ism: "Admin",
    familiya: "User",
    otasining_ismi: "System",
    tugilgan_yili: "1985",
    lavozimi: "Professor",
    telefon_raqami: "+998901234574",
    roli: "Admin",
    roli_internal: "Admin",
    user_id: "admin_001",
    username: "admin_01",
    password: "admin_01",
    kafedra_id: 0,
    department: "Robotics & Intelligent Systems",
  },
  {
    id: 2,
    ism: "Ahmad",
    familiya: "Karimov",
    otasining_ismi: "Alijon o'g'li",
    tugilgan_yili: "1980",
    lavozimi: "Kafedra mudiri",
    telefon_raqami: "+998901234567",
    roli: "Head of Department",
    roli_internal: "Kafedra mudiri",
    user_id: "user_001",
    username: "hod_ri_01",
    password: "hod_ri_01",
    kafedra_id: 1,
    department: "Robotics & Intelligent Systems",
    scopus_link: "https://www.scopus.com/authid/detail.uri?authorId=123456789",
    google_scholar_link: "https://scholar.google.com/citations?user=abc123",
    research_id_link: "https://www.researchgate.net/profile/Ahmad_Karimov",
  },
  {
    id: 3,
    ism: "Malika",
    familiya: "Toshmatova",
    otasining_ismi: "Rashid qizi",
    tugilgan_yili: "1975",
    lavozimi: "Professor",
    telefon_raqami: "+998901234568",
    roli: "Teacher",
    roli_internal: "O'qituvchi",
    user_id: "user_002",
    username: "teacher_ai_01",
    password: "teacher_ai_01",
    kafedra_id: 1,
    department: "Robotics & Intelligent Systems",
    scopus_link: "https://www.scopus.com/authid/detail.uri?authorId=987654321",
    google_scholar_link: "https://scholar.google.com/citations?user=def456",
    research_id_link: "https://www.researchgate.net/profile/Malika_Toshmatova",
  },
  {
    id: 4,
    ism: "Javohir",
    familiya: "Rahimov",
    otasining_ismi: "Sardor o'g'li",
    tugilgan_yili: "1985",
    lavozimi: "Dotsent",
    telefon_raqami: "+998901234569",
    roli: "Teacher",
    roli_internal: "O'qituvchi",
    user_id: "user_003",
    username: "teacher_robo_02",
    password: "teacher_robo_02",
    kafedra_id: 1,
    department: "Robotics & Intelligent Systems",
    scopus_link: "https://www.scopus.com/authid/detail.uri?authorId=456789123",
    google_scholar_link: "https://scholar.google.com/citations?user=ghi789",
  },
  {
    id: 5,
    ism: "Dilshoda",
    familiya: "Yusupova",
    otasining_ismi: "Farhod qizi",
    tugilgan_yili: "1990",
    lavozimi: "Katta o'qituvchi",
    telefon_raqami: "+998901234570",
    roli: "Teacher",
    roli_internal: "O'qituvchi",
    user_id: "user_004",
    username: "teacher_ai_02",
    password: "teacher_ai_02",
    kafedra_id: 1,
    department: "Robotics & Intelligent Systems",
    google_scholar_link: "https://scholar.google.com/citations?user=jkl012",
  },
  {
    id: 6,
    ism: "Farhod",
    familiya: "Saidov",
    otasining_ismi: "Akmal o'g'li",
    tugilgan_yili: "1992",
    lavozimi: "Assistent",
    telefon_raqami: "+998901234571",
    roli: "Teacher",
    roli_internal: "O'qituvchi",
    user_id: "user_005",
    username: "teacher_robo_03",
    password: "teacher_robo_03",
    kafedra_id: 1,
    department: "Robotics & Intelligent Systems",
  },
]

// Mock Methodical Works
export const mockMethodicalWorks: MethodicalWork[] = [
  {
    id: 1,
    nomi: "Introduction to Robotics",
    yili: "2023",
    nashiryot_nomi: "University Press",
    mualliflar: [3, 4], // Co-authors
    ish_turi: "Darslik",
    tili: "Ingliz",
    uslubiy_ish_fayli: "/demo/file1.pdf",
    nashr_ruxsat_fayli: "/demo/permit1.pdf",
    desc: "Comprehensive introduction to robotics fundamentals",
    created_by: 3,
    department_visible: true,
    created_at: "2023-01-15T10:00:00Z",
  },
  {
    id: 2,
    nomi: "Machine Learning Basics",
    yili: "2023",
    nashiryot_nomi: "Tech Publications",
    mualliflar: [3],
    ish_turi: "O'quv qo'llanma",
    tili: "Ingliz",
    uslubiy_ish_fayli: "/demo/file2.pdf",
    created_by: 3,
    created_at: "2023-02-20T11:00:00Z",
  },
  {
    id: 3,
    nomi: "Intelligent Systems Design",
    yili: "2024",
    nashiryot_nomi: "Academic Press",
    mualliflar: [4, 5],
    ish_turi: "Uslubiy qo'llanma",
    tili: "Ingliz",
    uslubiy_ish_fayli: "/demo/file3.pdf",
    nashr_ruxsat_fayli: "/demo/permit2.pdf",
    created_by: 4,
    department_visible: false,
    created_at: "2024-03-10T09:00:00Z",
  },
  {
    id: 4,
    nomi: "Robotics Programming",
    yili: "2024",
    nashiryot_nomi: "Tech Books",
    mualliflar: [4],
    ish_turi: "Uslubiy ko'rsatma",
    tili: "O'zbek",
    uslubiy_ish_fayli: "/demo/file4.pdf",
    created_by: 4,
    created_at: "2024-04-15T14:00:00Z",
  },
]

// Mock Research Works
export const mockResearchWorks: ResearchWork[] = [
  {
    id: 1,
    mualliflar: [3, 4],
    ilmiy_ish_nomi: "Advanced Robotics Applications",
    anjuman_yoki_jurnal_nomi: "IEEE Robotics Conference",
    yili: "2023",
    tili: "Ingliz",
    ilmiy_ish_turi: "Xorijiy maqola",
    ilmiy_ish_fayli: "/demo/research1.pdf",
    link: "https://doi.org/10.1109/ROBOT2023.123456",
    created_by: 3,
    department_visible: true,
    created_at: "2023-07-10T10:00:00Z",
  },
  {
    id: 2,
    mualliflar: [3],
    ilmiy_ish_nomi: "AI in Education",
    anjuman_yoki_jurnal_nomi: "International AI Journal",
    yili: "2023",
    tili: "Ingliz",
    ilmiy_ish_turi: "Xorijiy maqola",
    ilmiy_ish_fayli: "/demo/research2.pdf",
    created_by: 3,
    created_at: "2023-08-15T11:00:00Z",
  },
  {
    id: 3,
    mualliflar: [4],
    ilmiy_ish_nomi: "Neural Networks for Robotics",
    anjuman_yoki_jurnal_nomi: "Neural Computing Conference",
    yili: "2024",
    tili: "Ingliz",
    ilmiy_ish_turi: "Xorijiy tezis",
    ilmiy_ish_fayli: "/demo/research3.pdf",
    link: "https://doi.org/10.1000/NCC2024.789012",
    created_by: 4,
    department_visible: false,
    created_at: "2024-01-20T09:00:00Z",
  },
]

// Mock Certificates
export const mockCertificates: Certificate[] = [
  {
    id: 1,
    nomi: "Robotics Certification",
    yili: "2023",
    nashriyot_nomi: "Cisco Academy",
    mualliflar: [3],
    sertifikat_turi: "Xalqaro",
    tili: "Ingliz",
    sertifikat_fayli: "/demo/cert1.pdf",
    desc: "Advanced robotics course",
    created_by: 3,
    created_at: "2023-05-15T10:00:00Z",
  },
  {
    id: 2,
    nomi: "AI Specialization",
    yili: "2024",
    nashriyot_nomi: "Coursera",
    mualliflar: [3, 4],
    sertifikat_turi: "Xalqaro",
    tili: "Ingliz",
    sertifikat_fayli: "/demo/cert2.pdf",
    created_by: 3,
    department_visible: true,
    created_at: "2024-02-15T14:00:00Z",
  },
]

// Mock Software Certificates
export const mockSoftwareCertificates: SoftwareCertificate[] = [
  {
    id: 1,
    mualliflar: [3],
    nomi: "Robotics Simulation Platform",
    tasdiqlangan_sana: "2023-06-15",
    berilgan_joy: "University",
    guvohnoma_nomeri: "DGU-2023-001",
    guvohnoma_turi: "DGU",
    fayl_url: "/demo/softcert1.pdf",
    created_by: 3,
    created_at: "2023-06-15T10:00:00Z",
  },
  {
    id: 2,
    mualliflar: [4, 5],
    nomi: "AI Learning System",
    tasdiqlangan_sana: "2024-01-10",
    berilgan_joy: "University",
    guvohnoma_nomeri: "DGU-2024-012",
    guvohnoma_turi: "DGU",
    fayl_url: "/demo/softcert2.pdf",
    created_by: 4,
    department_visible: true,
    created_at: "2024-01-10T09:00:00Z",
  },
]

// Mock Files
export const mockFiles: File[] = [
  {
    id: 1,
    fayl_url: "/demo/file1.pdf",
    foydalanuvchi_id: 3,
    fayl_nomi: "Lecture_Notes_Week1.pdf",
    fayl_hajmi: "2.4 MB",
    created_at: "2024-01-15T10:00:00Z",
  },
  {
    id: 2,
    fayl_url: "/demo/file2.pdf",
    foydalanuvchi_id: 4,
    fayl_nomi: "Assignment_Template.docx",
    fayl_hajmi: "1.2 MB",
    created_at: "2024-01-20T11:00:00Z",
  },
  {
    id: 3,
    fayl_url: "/demo/file3.pdf",
    foydalanuvchi_id: 3,
    fayl_nomi: "Research_Paper.pdf",
    fayl_hajmi: "5.2 MB",
    created_at: "2024-02-25T14:00:00Z",
  },
]
